Controller: fix fallthrough annotation breaks compilation in older co…
prplfoundation/prplMesh-controller pull request #4
Opened 2019-05-27 08:53 UTC by LiorAmram

…mpilers

2019-05-27 11:06 UTC, tomereli requested changes
- Commit headline should be < 76 characters
- Commit message is empty - add explanation + links to relevant PRs in other repos

2019-05-27 13:46 UTC, arnout commented
> - Commit headline should be < 76 characters

Actually, the convention is to keep the headline <= 62 characters, because that
(usually) makes a `git log --oneline` fit on a 80-character line.

In practice, this convention is hard to maintain if you want to put a
`component: subcomponent: ...` part in front of it.

For the rest of the commit message, the convention is <= 72 characters.

2019-05-27 13:48 UTC, tomereli approved these changes

2019-05-27 13:49 UTC, tomereli requested changes
Please add a comment in the commit message for dependencies - since this commit depends on https://github.com/prplfoundation/prplMesh-common/pull/10

2019-05-27 14:13 UTC, arnout commented
While we're nit-picking on the commit message :-)

* The header tag should be either a component or a path. The path affected here is src/beerocks/master/db/network_map. We've kind of converged on using components, though. I don't really know what to call this component (beerocks? master? db?) but Tomer pushed commits earlier that use `db:` as the header tag, so I guess that is the one. `build:` is definitely wrong, that would apply to a change in a CMakeLists.txt or something similar.
* I don't think the "Elaborate" tag in the commit message is very useful; the commit message body *is* an elaboration.
* recplacing -> replacing

2019-05-28 07:27 UTC, tomereli requested changes
Please add a comment in the commit message for dependencies - since this commit depends on https://github.com/prplfoundation/prplMesh-common/pull/10

Dependencies - prplMesh-common (https://github.com/prplfoundation/prplMesh-common/pull/10)

2019-05-28 08:44 UTC, arnout approved these changes
> Please add a comment in the commit message for dependencies - since this commit depends on [prplfoundation/prplMesh-common#10](https://github.com/prplfoundation/prplMesh-common/pull/10)
> 
> Dependencies - prplMesh-common ([prplfoundation/prplMesh-common#10](https://github.com/prplfoundation/prplMesh-common/pull/10))

Although this is good principle in general - in this case, the PR in -common has already been merged yesterday. So I don't see the need to still mention that dependency. I mean, *everything* in -controller somehow depends on things in -common or -framework, so the list of dependencies could be very long :-)

2019-05-28 08:59 UTC, tomereli approved these changes

2019-05-28 08:59 UTC, merged